### ISSUE TITLE
Cannot process Asciidoc files residing in a (sub)project's root directory

### ISSUE THREAD

**Issue by pniederw** [asciidoctor/asciidoctor-gradle-plugin#169]
Environment:
Gradle 2.5
org.asciidoctor:asciidoctor-gradle-plugin:1.5.2
org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.8

Actions:
Put Asciidoc files in a (sub)project's root directory
Set `asciidoctor.sourceDir = projectDir`
Run `gradlew asciidoctor`

Outcome:
```
:docs:asciidoctor
Passing through unknown backend: pdf
:docs:asciidoctor FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:asciidoctor'.
> Error running Asciidoctor
```

Stack trace:
```
Caused by: org.gradle.api.GradleException: Error running Asciidoctor
	at org.asciidoctor.gradle.AsciidoctorTask.processDocumentsAndResources(AsciidoctorTask.groovy:659)
	at org.asciidoctor.gradle.AsciidoctorTask.this$4$processDocumentsAndResources(AsciidoctorTask.groovy)
	at org.asciidoctor.gradle.AsciidoctorTask$this$4$processDocumentsAndResources.callCurrent(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:592)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 69 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java_lang_StringBuilder$delete$0.call(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorUtils.getRelativePath(AsciidoctorUtils.groovy:57)
	at org.asciidoctor.gradle.AsciidoctorUtils$getRelativePath.call(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorTask.mergedOptions(AsciidoctorTask.groovy:701)
	at org.asciidoctor.gradle.AsciidoctorTask.processSingleFile(AsciidoctorTask.groovy:672)
	at org.asciidoctor.gradle.AsciidoctorTask$_processDocumentsAndResources_closure7.doCall(AsciidoctorTask.groovy:652)
	at org.asciidoctor.gradle.AsciidoctorTask.processDocumentsAndResources(AsciidoctorTask.groovy:647)
	... 80 more

```

**Comment by mojavelinux** [comment]
This appears to be a path calculation problem in the AsciidoctorUtils.getRelativePath method. Something that perhaps a unit test could address?

Interesting to note that Groovy now provides a relative path calculation method in JDK 7 or 8 called relativize. I wonder if we could use that instead.

**Comment by aalmiray** [comment]
If so, this will bring the discussion of supporting JDK6 or JDK7 as a minimum. The current build says JDK6 is the minimum but I believe it reality is JDK7. I have no problems pushing for JDK7 as the base :-)

**Comment by mojavelinux** [comment]
AsciidoctorJ is likely moving to JDK 7, so that's more validation for the
choice (since JRuby 9000 is JDK 7 min)

**Comment by ysb33r** [comment]
The main reason i a Gradle plugin to support JDK6 is because that is the minimum version itself supports. However if AsciidoctorJ 1.6 moves to JDK7, we'll have no choice but to make the minimum supported JDK to be 1.7.

I am sure the bug can be fixed without resorting to JDK7. I have used code similar to https://gist.github.com/ysb33r/5804364 to do this before. We can always release a 1.5.4 with some minimal fixes.

**Comment by mojavelinux** [comment]
By all means, if you can fix it without a major change, please proceed. I was simply mentioning as a side note that perhaps we could get out of the business of relative path calculations.

Perhaps we can plan for JDK 7 minimum for 1.6.0.

Btw, for the next micro release of the plugin, I recommend version 1.5.2.1 (or some other version modifier on 1.5.2). Users seem to be comfortable assuming that the first part of the version aligns with the version of Asciidoctor core used. But that doesn't prevent the plugin from being released if you can preserve that part.

**Comment by pniederw** [comment]
Sounds like https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/163 tries to address this problem.

**Comment by aalmiray** [comment]
#163 has been merged. Could you try the fix by building your own snapshot? :smile:

**Comment by robfletcher** [comment]
I hit the same issue and using a snapshot built from master fixed it

**Comment by IRus** [comment]
I get in similar issue. My goal is convert readme file to an html presentation (if you know better way than use this plugin - please tell me). So i write following build.gradle build file:

```groovy
plugins {
  id "org.asciidoctor.convert" version "1.5.2"
}

asciidoctor {
    sources {
        include 'README.adoc'
    }
    sourceDir = projectDir
    outputDir = projectDir
}
```
And get following error:
```
$ gradle asciidoctor
:asciidoctor

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task 'asciidoctor' during up-to-date check.  See stacktrace for details.
> Failed to create MD5 hash for file E:\Files\dev\awesome-kotlin\.gradle\2.6\taskArtifacts\cache.properties.lock.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.138 secs
```

@robfletcher how i can use snapshot version of plugin in my gradle build?

**Comment by IRus** [comment]
I tried build snapshot and use it, but still get same issue.

**Comment by aalmiray** [comment]
@IRus your problem is a bit different. You're setting up asciidoctor's `sourceDir` to be equal to the root project's dir. Gradle calculate's hashes for all inputs in order to figure out if something has changed. These hashes are stored inside the root project directory too. So you see, you're effectively telling gradle that the root project directory is updated every single time.

The solution is to place the sources and outputs in a different directory, just use the default settings and you should be fine.
