### ISSUE TITLE
Gradle task is unable to render a seemingly simple adoc and gives no output as to why

### ISSUE THREAD

**Issue by sebersole** [asciidoctor/asciidoctor-gradle-plugin#170]
````
[sebersole@t540 documentation] $ gradle renderProposal
...
:documentation:renderProposal
Converting /home/sebersole/projects/hibernate/hibernate-orm/documentation/proposal.adoc
:documentation:renderProposal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':documentation:renderProposal'.
> Error running Asciidoctor

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
````

Setting `--info` and `--debug` led to no additional useful information.  The task seems correct:
````
task renderProposal(type: AsciidoctorTask) {
    description = 'Renders the documentation proposal document.'
    sourceDir = project.projectDir
    outputDir = new File("$buildDir/tmp/proposal/html")
    backends "html5"
    separateOutputDirs false
    logDocuments true
    sources {
        include 'proposal.adoc'
    }
}
````

The task finds the document ok; we can see that in its lifecycle logging.

I even slimmed the document down to a VERY simple doc:

````
= Documentation proposal
:toc:

The intention is to overhaul the reference manual and re-integrate the pertinent information from the dev-guide.
We'd need to determine whether a separate dev-guide still makes sense.  The intention for the dev-guide was always to
describe SPI/integration concerns.  However some "user information" definitely made its way in there.

Order is still tbd

== Preface

See the updated preface from manual.

== Architecture

Describe Hibernate at a high-level.  See the updated page from manual.

== Domain Model

Describes the various aspects of the users domain model and mapping its.  See the `Data_Categorizations.xml` chapter
from the dev-guide for what I think is a great start.  It needs to be augmented from data in various chapters in
the current manual.
````

And the task still failed.

**Comment by mojavelinux** [comment]
This is the getRelativePath utility method error biting us again. You can see the problem when you add the `--stacktrace` flag to the Gradle command.

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java_lang_StringBuilder$delete.call(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorUtils.getRelativePath(AsciidoctorUtils.groovy:57)
	at org.asciidoctor.gradle.AsciidoctorUtils$getRelativePath.call(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorTask.mergedOptions(AsciidoctorTask.groovy:701)
	at org.asciidoctor.gradle.AsciidoctorTask.processSingleFile(AsciidoctorTask.groovy:672)
	at org.asciidoctor.gradle.AsciidoctorTask$_processDocumentsAndResources_closure7.doCall(AsciidoctorTask.groovy:652)
	at org.asciidoctor.gradle.AsciidoctorTask.processDocumentsAndResources(AsciidoctorTask.groovy:647)
	... 72 more
```

See #163 and #169.

**Comment by mojavelinux** [comment]
The (not ideal) workaround is to move the document from the root of the project to a sub-folder.

**Comment by sebersole** [comment]
That was it!  Thanks Dan!  Moving it into a sub-directory did in fact resolve the problem.
