### ISSUE TITLE
Add support for JBake 2.4.0

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoctor-gradle-plugin#172]
Preliminary, minimal testing with 2.4.0 resulted in the following error:

    Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'memory' was not found. URL was: memory:cache. Registered engines are: []at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:208)
        at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.exists(ODatabaseRaw.java:206)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.exists(ODatabaseWrapperAbstract.java:65)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.exists(ODatabaseWrapperAbstract.java:65)
        at org.jbake.app.ContentStore.<init>(ContentStore.java:49)
        at org.jbake.app.DBUtil.createDataStore(DBUtil.java:18)
        at org.jbake.app.Oven.bake(Oven.java:133)
        at me.champeau.gradle.JBakeTask$_bake_closure1.doCall(JBakeTask.groovy:38)
        at me.champeau.gradle.JBakeTask.bake(JBakeTask.groovy:35)

Reverting to `2.3.2` in the buildscript classpath made the error go away.

**Comment by msgilligan** [comment]
Sorry, I meant to open this on the JBake plugin.
