### ISSUE TITLE
Fix issue running AsciidoctorJ out of  process on Gradle 4.10

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#269]
Running something like

```groovy
asciidoctorPdf {
    inProcess OUT_OF_PROCESS
    logDocuments true
    sourceDir 'src/docs/asciidoc'

    sources {
        include 'subdir/sample2.ad'
    }
}
```

will fail with an error

```
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.12 and you are trying to load version 2.4.15
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:513)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:80)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:74)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:56)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:113)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:74)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
```

**Comment by ragnor** [comment]
Hi,
Is there any way to run version 1.5.9.2 on gradle 5.1.1 so below exception won't occur:
{code}
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
        at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
        at groovy.lang.Reference.<init>(Reference.java:38)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:188)
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.5.4 and you are trying to load version 2.4.12
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:523)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:81)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModulesFrom(ExtensionModuleScanner.java:63)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:55)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:124)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        ... 5 more
{code}

**Comment by ysb33r** [comment]
Try using 2.0-alpha.5 instead.

**Comment by ragnor** [comment]
Thank you for the answer. 
Unfortunately I'm using Spring REST Docs that requires asciidoctor 1.5.x. What is surprising downgrading to 1.5.3 (this one is suggested in Spring REST Docs documentation) seams to solve the issue.
With 2.0-alpha.5 and gradle 5.1.1 I had an issue `Exception in thread "main" java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet$SerializedForm`

**Comment by shevek** [comment]
Asciidoctor doesn't work on 4.10.3 either.

**Comment by wimdeblauwe** [comment]
Also had to downgrade to 1.5.3 to work with Gradle 5.2.1

**Comment by ysb33r** [comment]
@wimdeblauwe @shevek @ragnor Are any of you using `build.gradle.kts` instead of `build.gradle` ?

**Comment by wimdeblauwe** [comment]
> @wimdeblauwe @shevek @ragnor Are any of you using `build.gradle.kts` instead of `build.gradle` ?

Not me

**Comment by shevek** [comment]
We are using build.gradle in groovy, no kts here.

**Comment by shevek** [comment]
The issue is that AbstractAsciidoctorTask is including everything plus the kitchen sink on the classpath when it invokes an external JVM. Heaven only knows why half that stuff is on there, there's at least 3 groovy versions that I can see. It's including the entire runtime classpath for the project without even doing dependency resolution. So yes, it's SNAFU'd.

**Comment by ysb33r** [comment]
I think I have tracked down the issue. I might do a maintenance release within the next two weeks. Time is limited atm.

**Comment by ysb33r** [comment]
Finally got to do the fix for this after 2.1.0 was released and 2.2.0 work has bene prepped. 

The fix will be released in 1.5.12 and 1.6.1. Will get @aalmiray to release when he has the time.

**Comment by shevek** [comment]
Is there a release of 1.5.12? asciidoctor just broke for us globally with no change on our side, so we're hunting for a bunch of outstanding fixes. :(

**Comment by ysb33r** [comment]
Yes 1.5.12 & 1.6.1 was released some weeks ago.

**Comment by shevek** [comment]
Thank you. Didn't see it on Central. See it now in Gradle plugins.

**Comment by ysb33r** [comment]
Closing thisissue. Please raise a new one if you still see something similar.
