### ISSUE TITLE
SecurityError when baseDir is set

### ISSUE THREAD

**Issue by lwolter** [asciidoctor/asciidoctor-gradle-plugin#325]
If baseDir is not set, asciidoctor will search the include files not in the source directory but in the project root directory.

```groovy
plugins {
    id 'org.asciidoctor.jvm.convert' version '2.0.0'
    id 'org.asciidoctor.jvm.base' version '2.0.0'
}

repositories {
    jcenter()
}

asciidoctor {
    sourceDir 'src/doc'
    baseDir 'src/doc'

    sources {
        include '*.adoc'
    }
    
}
```

```
Apr 04, 2019 11:11:30 AM org.asciidoctor.internal.JRubyAsciidoctor convertFile
SCHWERWIEGEND: (SecurityError) to_dir /home/lwolter/prj/Koeln/build/docs/asciidoc is outside of jail: /home/lwolter/prj/Koeln/src/doc (disallowed in safe mode)
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /home/lwolter/prj/Koeln/src/doc/personOccupancy.adoc using backend html5
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2163)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:65)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.access$1(AsciidoctorJavaExec.groovy)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure2.doCall(AsciidoctorJavaExec.groovy:57)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure2.call(AsciidoctorJavaExec.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:51)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:128)
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.SecurityError: (SecurityError) to_dir /home/lwolter/prj/Koeln/build/docs/asciidoc is outside of jail: /home/lwolter/prj/Koeln/src/doc (disallowed in safe mode)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:469)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:70)
	... 22 more
Caused by: org.jruby.exceptions.SecurityError: (SecurityError) to_dir /home/lwolter/prj/Koeln/build/docs/asciidoc is outside of jail: /home/lwolter/prj/Koeln/src/doc (disallowed in safe mode)
	at RUBY.system_path(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/path_resolver.rb:364)
	at RUBY.normalize_system_path(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_node.rb:475)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1491)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1157)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)

> Task :asciidoctor FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctor'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
```

**Comment by mojavelinux** [comment]
If you set the baseDir, you almost always have to set the safe mode to unsafe. This is a limitation in Asciidoctor core. Until addressed, that's just how it works.

However, generally I don't recommend setting the baseDir right now (unless you know what you are doing with it) because it has this limitation.

In short, either don't set baseDir or set the safe mode to unsafe.

**Comment by ysb33r** [comment]
@lwolter There is something to address in the README about this situation as you are not the only one caught out by this. The are some solutions to this issue.

Firstly when rendering ASciideoctor documents with Gradle it is best to always use `{includedir}` for instance

```
include::{includedir}file.adoc[]

include::{includedir}/subdir/file.adoc[]
```

Gradle will always set `includedir` to the correct location even when it needs to relocate source to an intermediate working directory. In this way you can be assured that your source will always be found.

`baseDir` is always set to the root project in Gradle by default. This is something that was came out of usage cases in older version of the plugin. It allows for sources to be pulled safely out of multiple subprojects. 

You can always change the security mode by doing one of these:

```groovy
asciidoctorj {
  safeMode UNSAFE 
  safeMode 'unsafe'
}

**Comment by lwolter** [comment]
The following setting worked. Thank you. I use baseDir because there are already many files without includedir.

`asciidoctorj {
    safeMode 'unsafe'
}`
