### ISSUE TITLE
Exception rendering pdf with Noto Color Emoji (NoMethodError) undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by ieugen** [asciidoctor/asciidoctor-gradle-plugin#553]
Hi,

I'm getting an exception rendering a document to pdf with color emoji provided by Noto https://www.google.com/get/noto/#emoji-zsye-color .

The document is like this:

index.adoc
```
= Hello
Emoji friendly: © 😀
```

I'm using this theme:

```
extends: default
font:
  catalog:
    Noto Sans:
      normal: NotoSans-Regular.ttf
      italic: NotoSans-Italic.ttf
      bold: NotoSans-Bold.ttf
      bold_italic: NotoSans-BoldItalic.ttf
    Noto Serif:
      normal: NotoSerif-Regular.ttf
      italic: NotoSerif-Italic.ttf
      bold: NotoSerif-Bold.ttf
      bold_italic: NotoSerif-BoldItalic.ttf
    Noto Emoji:
      normal: NotoEmoji-Regular.ttf
      italic: NotoEmoji-Regular.ttf
      bold: NotoEmoji-Regular.ttf
      bold_italic: NotoEmoji-Regular.ttf
    # Color Emoji does not currently work
    Noto Color Emoji:
      normal: NotoColorEmoji.ttf
      italic: NotoColorEmoji.ttf
      bold: NotoColorEmoji.ttf
      bold_italic: NotoColorEmoji.ttf
    # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
  fallbacks: [Noto Color Emoji, Noto Emoji]
base:
  font:
    family: Noto Serif
    # color: #ffa3bb
heading:
  font:
    family: Noto Serif
```

And this gradle config:

build.gradle
````
plugins {
    id 'org.asciidoctor.jvm.convert' version '3.1.0'
    id 'org.asciidoctor.jvm.pdf' version '3.1.0'
}

asciidoctor {
  languages 'en', 'ro'
  outputDir  file('build/docs')
}
asciidoctorj {
  modules {
    pdf {
      version '1.5.3'
    }
  }
}
asciidoctorPdf {
  fontsDir 'src/fonts'
  theme 'non-zero-sum'
}
pdfThemes {
    local 'non-zero-sum', {
        themeDir = file('src/themes/non-zero-sum')
        themeName = 'non-zero-sum'
    }
}
repositories {
    jcenter()
    mavenCentral()
}
````

````
Running AsciidoctorJ instance with classpath [/home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctor-gradle-jvm/3.1.0/e3d639383eb6036034610a5afb1c240a0f3915cd/asciidoctor-gradle-jvm-3.1.0.jar, /home/ieugen/.sdkman/candidates/gradle/6.5/lib/groovy-all-1.3-2.5.11.jar, /home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/2.2.0/1ac831d40e76904cbe80c2234841f35650ff260/asciidoctorj-2.2.0.jar, /home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.3/ccaccbef0af5b5e836ff983f5ed682ff3e063851/asciidoctorj-pdf-1.5.3.jar, /home/ieugen/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar, /home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-api/2.2.0/4a849cb21daf392025b07d66d559aed552c9d7c5/asciidoctorj-api-2.2.0.jar, /home/ieugen/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar, /home/ieugen/.sdkman/candidates/gradle/6.5/lib/guava-27.1-android.jar]
Starting process 'command '/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java''. Working directory: /home/ieugen/proiecte/branding-and-identity/brand-book Command: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java -Dfile.encoding=UTF-8 -Duser.country=RO -Duser.language=ro -Duser.variant -cp /home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctor-gradle-jvm/3.1.0/e3d639383eb6036034610a5afb1c240a0f3915cd/asciidoctor-gradle-jvm-3.1.0.jar:/home/ieugen/.sdkman/candidates/gradle/6.5/lib/groovy-all-1.3-2.5.11.jar:/home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/2.2.0/1ac831d40e76904cbe80c2234841f35650ff260/asciidoctorj-2.2.0.jar:/home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.3/ccaccbef0af5b5e836ff983f5ed682ff3e063851/asciidoctorj-pdf-1.5.3.jar:/home/ieugen/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar:/home/ieugen/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-api/2.2.0/4a849cb21daf392025b07d66d559aed552c9d7c5/asciidoctorj-api-2.2.0.jar:/home/ieugen/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar:/home/ieugen/.sdkman/candidates/gradle/6.5/lib/guava-27.1-android.jar org.asciidoctor.gradle.remote.AsciidoctorJavaExec /home/ieugen/proiecte/branding-and-identity/brand-book/build/tmp/asciidoctorPdf.javaexec-data
Successfully started process 'command '/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java''
Iun 07, 2020 4:50:56 PM org.asciidoctor.jruby.internal.JRubyAsciidoctor convertFile
SEVERE: (NoMethodError) undefined method `key?' for nil:NilClass
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /home/ieugen/proiecte/branding-and-identity/brand-book/src/docs/asciidoc/ro/index.adoc using backend pdf
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2368)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:80)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.access$1(AsciidoctorJavaExec.groovy)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.doCall(AsciidoctorJavaExec.groovy:72)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:67)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:49)
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `key?' for nil:NilClass
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:400)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:366)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:85)
        ... 22 more
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `key?' for nil:NilClass
        at uri_3a_classloader_3a_.gems.ttfunk_minus_1_dot_5_dot_1.lib.ttfunk.table.glyf.for(uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/table/glyf.rb:30)
        at uri_3a_classloader_3a_.gems.ttfunk_minus_1_dot_5_dot_1.lib.ttfunk.subset.base.collect_glyphs(uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:158)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1814)
        at org.jruby.RubyEnumerable.each_with_object(org/jruby/RubyEnumerable.java:1273)
        at RUBY.collect_glyphs(uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:157)
        at RUBY.encode(uri:classloader:/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:32)
        at RUBY.embed(uri:classloader:/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:261)
        at RUBY.register(uri:classloader:/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:255)
        at RUBY.before_render_actions(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1814)
        at RUBY.before_render_actions(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62)
        at RUBY.render_header(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:188)
        at RUBY.render(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:164)
        at RUBY.render(uri:classloader:/gems/prawn-2.2.2/lib/prawn/document.rb:378)
        at RUBY.render_file(uri:classloader:/gems/prawn-2.2.2/lib/prawn/document.rb:386)
        at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1160)
        at RUBY.render_file(uri:classloader:/gems/prawn-2.2.2/lib/prawn/document.rb:386)
        at RUBY.write(uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3589)
        at RUBY.write(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:978)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:124)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183)
        at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1160)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183)
````

**Comment by ieugen** [comment]
Using   `fallbacks: [Noto Emoji]` instead of `  fallbacks: [Noto Color Emoji, Noto Emoji]` renders the pdf.

**Comment by Mogztter** [comment]
It seems related to this specific font. Could you please try to convert it using `asciidoctor-pdf` directly?
If you can reproduce it then we should probably transfer this issue upstream (ie. to https://github.com/asciidoctor/asciidoctor-pdf).

**Comment by abelsromero** [comment]
@Mogztter I was already working on it and it reproduces the exact same error (see log below). However, I think the problem is that NoteColorEmoji is just not valid.
Opening NotoColorEmoji with FontForge indicates the file is not valid or unreadable. Furthermore, I found this https://github.com/asciidoctor/asciidoctor-pdf/issues/1129. With the mentioned included fallback theme "default-with-fallback-font" I could render the PDF here, but the embedded font only contains a small subset of black&white emojis. That is for size reason, which to me seems reasonable.

```
Traceback (most recent call last):
        30: from /home/asalgadr/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
        29: from /home/asalgadr/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
        28: from /home/asalgadr/.rvm/gems/ruby-2.7.0/bin/asciidoctor-pdf:23:in `<main>'
        27: from /home/asalgadr/.rvm/gems/ruby-2.7.0/bin/asciidoctor-pdf:23:in `load'
        26: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:27:in `<top (required)>'
        25: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        24: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
        23: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
        22: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
        21: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
        20: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
        19: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:124:in `convert'
        18: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:978:in `write'
        17: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb:3589:in `write'
        16: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `render_file'
        15: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `open'
        14: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `block in render_file'
        13: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/document.rb:378:in `render'
        12: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:164:in `render'
        11: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:188:in `render_header'
        10: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `before_render_actions'
         9: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `each'
         8: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `block in before_render_actions'
         7: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:255:in `block in register'
         6: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:261:in `embed'
         5: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:32:in `encode'
         4: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:157:in `collect_glyphs'
         3: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:157:in `each_with_object'
         2: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:157:in `each'
         1: from /home/asalgadr/.rvm/gems/ruby-2.7.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:158:in `block in collect_glyphs'

```

**Comment by mojavelinux** [comment]
Asciidoctor PDF doesn't support color emoji because the font embedding library we use doesn't support color emoji. See https://github.com/prawnpdf/prawn/issues/1081.

**Comment by ieugen** [comment]
Thanks @mojavelinux . I think we can close the issue here.

One thing I believe it is nice to have as a gradle task is font validation. 

If a theme registers fonts in the catalog, it would be nice to have a validation step where prawn checks the font. 

It's the fail fast principle. It should avoid these kind of issues from popping up in the future or at least more informed users. 

WDYT?

**Comment by ysb33r** [comment]
> Thanks @mojavelinux . I think we can close the issue here.
> 
> One thing I believe it is nice to have as a gradle task is font validation.
> 
> If a theme registers fonts in the catalog, it would be nice to have a validation step where prawn checks the font.
> 

Sounds like a worthwhile addition. If we know what Ruby code to execute for the validation, then creating a Gradle task would be possible. 

It does add some complications though. The PDF plugin does not use the JRuby plugin, as it relies on the fact the all of the necessary Ruby is already packaged in the asciidoctorj-pdf JAR. If we do this, we'll probably have to add an additional plugin, so as to not burden PDF users with the additional classpath if they don't require it..

**Comment by ieugen** [comment]
Then maybe the validation can be done in asciidoctor-pdf as a CLI Param and a library option and exposed to the consumers.

**Comment by mojavelinux** [comment]
The role of the converter is to convert, not validate. Adding validation violates the separation of concern. It should be a separate tool (though it can certainly be integrated transparently / automatically).

**Comment by ieugen** [comment]
From what I can see in the docs it does command line parsing so it should do some input validation IMO. But then again I'm not very knowledgeable of the project's internals to have a good opinion. It's just my first impression. 

I'll close this issue then.
