### ISSUE TITLE
Plugin is incompatible with Gradle 8.1.1

### ISSUE THREAD

**Issue by iwnek-s8** [asciidoctor/asciidoctor-gradle-plugin#673]
Line:

https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L518

Stacktrace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctorPdf'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
...
Caused by: java.lang.NoSuchMethodError: 'void org.gradle.workers.WorkerExecutor.submit(java.lang.Class, org.gradle.api.Action)'
        at org.asciidoctor.gradle.jvm.AbstractAsciidoctorTask$_runWithWorkers_closure10.doCall(AbstractAsciidoctorTask.groovy:518)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

Gradle migration guide message:

```
The deprecated submit(Class, Action) method of the WorkerExecutor interface has been removed. Instead, obtain a WorkQueue via the noIsolation(), classLoaderIsolation(), and processIsolation(), methods and use the submit(Class, Action) method on the WorkQueue instead.
```

https://docs.gradle.org/current/userguide/upgrading_version_7.html#workerexecutor_api_cleanup

**Comment by ysb33r** [comment]
This is being worked on

**Comment by Goooler** [comment]
Links #664.
